spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: test
    password: test

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true