spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: test
    password: test

  # jpa 설정
  jpa:
    # 콘솔에 sql 표시
    show-sql: true
    properties:
      # Hibernate 설정
      hibernate:
        # SQL 쿼리문 포맷
        format_sql: true
    # SpringBoot 애플리케이션 시작 시 데이터베이스 초기화
    defer-datasource-initialization: true

  # h2 기본 설정 (console)
  h2:
    console:
      enabled: true


# JWT 토큰 설정
jwt:
  issuer: zesthj@gmail.com
  secret_key: springboot-jwt